### ISSUE TITLE
simulation

### ISSUE THREAD

**Issue by Wangmmstar** [UT-Austin-RobIn/BUMBLE#1]
Thank you for your wonderful work. I wonder if this supports the simulation platform as getting a real taiko robot is hard. If so, which platform did you use? If not, can it support other robot platforms? Do you have any recommendations regarding the occupancy map generation? Thank you in advance.

**Comment by ShahRutav** [comment]
Thanks for the interest in our work!
- To test VLM models and debug them more quickly, I collected images from a camera and used them to set up individual parts of the pipeline.
-  We do not have support for the simulation platform. [Behavior 1k](https://behavior.stanford.edu/behavior-1k) might be a good alternative since they have action primitives + photorealistic rendering.
- We used [gmapping](https://wiki.ros.org/gmapping) package for creating the static 2d map of each floor. You can use any robot to create this map. The mapping process is sensitive to sudden changes in the environment (w.r.t. previous time steps). Make sure you move the robot slowly and avoid rotations. 

Hope this helps!

**Comment by Wangmmstar** [comment]
> Thanks for the interest in our work!
> 
> * To test VLM models and debug them more quickly, I collected images from a camera and used them to set up individual parts of the pipeline.
> * We do not have support for the simulation platform. [Behavior 1k](https://behavior.stanford.edu/behavior-1k) might be a good alternative since they have action primitives + photorealistic rendering.
> * We used [gmapping](https://wiki.ros.org/gmapping) package for creating the static 2d map of each floor. You can use any robot to create this map. The mapping process is sensitive to sudden changes in the environment (w.r.t. previous time steps). Make sure you move the robot slowly and avoid rotations.
> 
> Hope this helps!

Thank you very much for your swift and detailed response. Will follow your guidance to test. Hope you have great rest of your day :).

**Comment by ShahRutav** [comment]
No worries! Closing this issue. Feel free to reopen this one or open a new one in the future!
